export enum EnvKeys {
  PORT = 'PORT',
  NODE_ENV = 'NODE_ENV',
  CONTEXT_PATH = 'CONTEXT_PATH',
  CORS_ORIGIN = 'CORS_ORIGIN',

  // session
  SESSION_SECRET = 'SESSION_SECRET',
  SESSION_MAX_AGE = 'SESSION_MAX_AGE',
  SESSION_SECURE = 'SESSION_SECURE',

  // app
  APP_ID = 'APP_ID',

  // logging
  LOG_LEVEL = 'LOG_LEVEL',
  LOG_PRETTY = 'LOG_PRETTY',

  // Redis
  REDIS_URL = 'REDIS_URL',
  DATA_NAMESPACE = 'DATA_NAMESPACE',

  FALLBACK_LANGUAGE = 'FALLBACK_LANGUAGE',
}
